package main

import (
	"fmt"
	"mapreduce"
	"os"
	"strconv"
	"strings"
	"unicode"
)

// The mapping function is called once for each piece of the input.
// In this framework, the key is the name of the file that is being processed,
// and the value is the file's contents. The return value should be a slice of
// key/value pairs, each represented by a mapreduce.KeyValue.
func mapF(document string, value string) (res []mapreduce.KeyValue) {
	// Declare the slice that will contain the result
	var result []mapreduce.KeyValue

	// Iterate over the words of the document, those that satisfy the isLetter function are added to the result slice
	for _, word := range strings.FieldsFunc(value, func(c rune) bool {
		return !unicode.IsLetter(c)
	}) {
		result = append(result, mapreduce.KeyValue{Key: word, Value: "1"})
	}

	return result
}

// The reduce function is called once for each key generated by Map, with a
// list of that key's string value (merged across all inputs). The return value
// should be a single output value for that key.
func reduceF(key string, values []string) string {
	// Declare an accumulator to hold the final key sum
	keySum := 0

	// Iterate over the key values
	for _, singleValue := range values {
		// Try to convert each value to integer
		singleInteger, err := strconv.Atoi(singleValue)

		// If the conversion succeeds, add it to the key sum
		if err == nil {
			keySum += singleInteger
		}
	}

	return strconv.Itoa(keySum)
}

// Can be run in 3 ways:
// 1) Sequential (e.g., go run wc.go master sequential x1.txt .. xN.txt)
// 2) Master (e.g., go run wc.go master localhost:7777 x1.txt .. xN.txt)
// 3) Worker (e.g., go run wc.go worker localhost:7777 localhost:7778 &)
func main() {
	if len(os.Args) < 4 {
		fmt.Printf("%s: see usage comments in file\n", os.Args[0])
	} else if os.Args[1] == "master" {
		var mr *mapreduce.Master
		if os.Args[2] == "sequential" {
			mr = mapreduce.Sequential("wcseq", os.Args[3:], 3, mapF, reduceF)
		} else {
			mr = mapreduce.Distributed("wcseq", os.Args[3:], 3, os.Args[2])
		}
		mr.Wait()
	} else {
		mapreduce.RunWorker(os.Args[2], os.Args[3], mapF, reduceF, 100)
	}
}
